echo "\n-----------Running mp1indexing-----------\n"
make run file="data/text/mp1indexing.txt"
echo "\n-----------Running mp1req1-----------\n"
make run file="data/text/mp1req1.txt"
echo "\n-----------Running mp1req2-----------\n"
make run file="data/text/mp1req2.txt"
echo "\n-----------Running mp1depth-----------\n"
make run file="data/text/mp1depth.txt"
echo "\n-----------Running mp1srgb-----------\n"
make run file="data/text/mp1srgb.txt"

echo "\n-----------scipt finished!-----------"